import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import './globals.css'
import '@/components/toasts/toasts.css'
import ParentProvider from './provider'


const open_sans = Open_Sans({ 
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={open_sans.className}>
        {/* custom providers here */}
        <ParentProvider>
          {children}
        </ParentProvider>

      </body>
    </html>
  )
}
